Repository mayadata-io/oep-e2e-rancher, pull requests merged in 2020-07, with the labels that each got.

#47 Added cluster-name in all the jobs for RANCHER platform
  stages/chaos/Jiva-App-kill/jiva-app-kill
  stages/chaos/Jiva-Controller-Network-Delay/ctrl-network-delay
  stages/chaos/Jiva-Controller-kill/jiva-controller-kill
  stages/chaos/Jiva-Replica-Network-Delay/jiva-replica-network-delay
  stages/chaos/Jiva-Replica-Node-Affinity/rep-node-affinity
  stages/chaos/Jiva-revision-counter/jiva-revision-counter
  stages/chaos/cstor-App-pod-kill/app-kill
  stages/chaos/cstor-Target-kill/target-kill
  stages/cluster-cleanup/cleanup
  stages/cluster-cleanup/cluster2-cleanup
  stages/cluster-cleanup/cluster3-cleanup
  stages/cluster-cleanup/e2e-metrics
  stages/cluster-cleanup/selenium-grid-cleanup
  stages/cluster-connect/client-components-check
  stages/cluster-connect/client3-components-check
  stages/cluster-connect/cluster-connect
  stages/cluster-connect/cluster3-connect
  stages/cluster-connect/create-apikey
  stages/cluster-setup/cluster2-setup
  stages/cluster-setup/cluster3-setup
  stages/cluster-setup/setup
  stages/director-gui/create-cstor-sc
  stages/director-gui/gui-dmaas-cstor-aws
  stages/director-gui/gui-dmaas-cstor-minio
  stages/director-gui/gui-dmaas-delete-minio
  stages/director-gui/gui-dmaas-device-aws
  stages/director-gui/gui-dmaas-device-minio
  stages/director-gui/gui-dmaas-hostpath-aws
  stages/director-gui/gui-dmaas-hostpath-minio
  stages/director-gui/gui-dmaas-jiva-aws
  stages/director-gui/gui-dmaas-jiva-minio
  stages/director-gui/run-gui-tests
  stages/functional/Jiva-App-Target-Affinity/app-target-affinity
  stages/functional/Jiva-Snapshot-Clone/jiva-snapshot-clone
  stages/functional/Jiva-Volume-Scaleup/jiva-vol-scaleup
  stages/functional/Jiva-snapshot/jiva-snapshot
  stages/functional/cstor-csi-volume-clone/csi-cstor-clone
  stages/functional/cstor-csi-volume-snapshot/csi-cstor-snapshot
  stages/functional/cstor-ext4-volume-resize/csi-volume-resize
  stages/functional/cstor-xfs-volume-resize/csi-volume-resize-xfs
  stages/functional/local-pv-device/local-pv-device
  stages/functional/local-pv-hostpath/local-pv-hostpath
  stages/functional/localpv-provisioning-selected-device/localpv-provisioning-selected-device
  stages/infra-setup/TCID-DIR-INSTALL-ON-LOCAL-HP
  stages/infra-setup/selenium-grid-deploy
  stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-MIRROR
  stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-RAIDZ
  stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE
  stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-MIRROR
  stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-NO-NDM
  stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-RAIDZ
  stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-STRIPE
  stages/openebs-install/TCID-DIR-OP-DELETE-CSPC-WITH-NO-VOLUME
  stages/openebs-install/TCID-DIR-OP-DELETE-SPC-WITH-NO-VOLUME
  stages/openebs-install/TCID-DIR-OP-INSTALL-OPENEBS
  stages/openebs-install/TCID-DIR-OP-INSTALL-OPENEBS-CP-ON-SPECIFIC-NODE
  stages/openebs-install/TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE
  stages/openebs-install/TCID-DIR-OP-INSTALL-OPENEBS-LIMIT-RESOURCE
  stages/openebs-install/TCID-DIR-OP-RE-INSTALL-OPENEBS
  stages/openebs-install/openebs-storage-policies
Labels: enhancement

#51 Passing openebs version as an env variable in RANCHER pipeline
  stages/openebs-install/TCID-DIR-OP-RE-INSTALL-OPENEBS
Labels: bug

#54 Restic privilege update
  .gitlab-ci.yml
  stages/director-gui/patch-restic-privilege
  stages/director-gui/templates/hub.yml
Labels: rancher

#55 feat(install): install Kubera On-Prem and OpenEBS using Kubera charts
  stages/infra-setup/TCID-DIR-INSTALL-ON-LOCAL-HP
Labels: enhancement, install
